// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "github.com/apache/thrift/lib/go/thrift"
        "weatherService"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  i64 login(Location location)")
  fmt.Fprintln(os.Stderr, "  bool logout(i64 sessionToken)")
  fmt.Fprintln(os.Stderr, "  bool sendWeatherReport(WeatherReport report, i64 sessionToken)")
  fmt.Fprintln(os.Stderr, "  WeatherReport receiveForecastFor(i64 userId, dateTime time)")
  fmt.Fprintln(os.Stderr, "  WeatherWarning checkWeatherWarnings(i64 userId)")
  fmt.Fprintln(os.Stderr, "  bool sendWarning(SystemWarning systemWarning, i64 userId)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := weatherService.NewWeatherClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "login":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Login requires 1 args")
      flag.Usage()
    }
    arg14 := flag.Arg(1)
    mbTrans15 := thrift.NewTMemoryBufferLen(len(arg14))
    defer mbTrans15.Close()
    _, err16 := mbTrans15.WriteString(arg14)
    if err16 != nil {
      Usage()
      return
    }
    factory17 := thrift.NewTJSONProtocolFactory()
    jsProt18 := factory17.GetProtocol(mbTrans15)
    argvalue0 := weatherService.NewLocation()
    err19 := argvalue0.Read(jsProt18)
    if err19 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Login(context.Background(), value0))
    fmt.Print("\n")
    break
  case "logout":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "Logout requires 1 args")
      flag.Usage()
    }
    argvalue0, err20 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err20 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.Logout(context.Background(), value0))
    fmt.Print("\n")
    break
  case "sendWeatherReport":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SendWeatherReport requires 2 args")
      flag.Usage()
    }
    arg21 := flag.Arg(1)
    mbTrans22 := thrift.NewTMemoryBufferLen(len(arg21))
    defer mbTrans22.Close()
    _, err23 := mbTrans22.WriteString(arg21)
    if err23 != nil {
      Usage()
      return
    }
    factory24 := thrift.NewTJSONProtocolFactory()
    jsProt25 := factory24.GetProtocol(mbTrans22)
    argvalue0 := weatherService.NewWeatherReport()
    err26 := argvalue0.Read(jsProt25)
    if err26 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1, err27 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err27 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.SendWeatherReport(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "receiveForecastFor":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ReceiveForecastFor requires 2 args")
      flag.Usage()
    }
    argvalue0, err28 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err28 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := weatherService.DateTime(argvalue1)
    fmt.Print(client.ReceiveForecastFor(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "checkWeatherWarnings":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "CheckWeatherWarnings requires 1 args")
      flag.Usage()
    }
    argvalue0, err30 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err30 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.CheckWeatherWarnings(context.Background(), value0))
    fmt.Print("\n")
    break
  case "sendWarning":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SendWarning requires 2 args")
      flag.Usage()
    }
    tmp0, err := (strconv.Atoi(flag.Arg(1)))
    if err != nil {
      Usage()
     return
    }
    argvalue0 := weatherService.SystemWarning(tmp0)
    value0 := argvalue0
    argvalue1, err31 := (strconv.ParseInt(flag.Arg(2), 10, 64))
    if err31 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.SendWarning(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
